/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ChatApplication.Client;

import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author sohai
 */
public class HomeGUI extends javax.swing.JFrame
{
    public User user;
    public static String sender = null;
    public static String receiver = null;
    DefaultListModel model = new DefaultListModel();
    
    
    /**
     * Creates new form HomeGUI
     */
    public HomeGUI(User user)
    {
        this.user = user;
        sender = this.user.getRollNo();
        initComponents();
        nameLabel.setText(this.user.getRollNo());
        chatBox.setLineWrap(true);
        messageField.setLineWrap(true);
        chatsList.setModel(model);
        addChatList();
    }
    
    public void addChatList()
    {
        DbUtil.initChatList(model, user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatsList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        sendBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        usernameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(30, 42, 54));

        jScrollPane1.setBorder(null);

        chatsList.setBackground(new java.awt.Color(30, 42, 54));
        chatsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chatsList.setForeground(new java.awt.Color(255, 255, 255));
        chatsList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                chatsListMouseClicked(evt);
            }
        });
        chatsList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                chatsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(chatsList);

        jPanel2.setBackground(new java.awt.Color(34, 47, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sendBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        chatBox.setEditable(false);
        chatBox.setBackground(new java.awt.Color(44, 62, 80));
        chatBox.setColumns(20);
        chatBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chatBox.setForeground(new java.awt.Color(255, 255, 255));
        chatBox.setRows(5);
        chatBox.setBorder(null);
        jScrollPane3.setViewportView(chatBox);

        messageField.setBackground(new java.awt.Color(44, 62, 80));
        messageField.setColumns(20);
        messageField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageField.setForeground(new java.awt.Color(255, 255, 255));
        messageField.setRows(5);
        messageField.setText("Type a Message...");
        jScrollPane2.setViewportView(messageField);

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBtn)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(sendBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sendBtnActionPerformed
    {//GEN-HEADEREND:event_sendBtnActionPerformed

    }//GEN-LAST:event_sendBtnActionPerformed

    private void chatsListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_chatsListValueChanged
    {//GEN-HEADEREND:event_chatsListValueChanged

    }//GEN-LAST:event_chatsListValueChanged

    private void chatsListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_chatsListMouseClicked
    {//GEN-HEADEREND:event_chatsListMouseClicked
        receiver = usernameLabel.getText();
        chatBox.setText(null);
        User temp = (User) chatsList.getSelectedValue();
        usernameLabel.setText(temp.getName());
        DbUtil.showChat(temp.getRollNo(), user.getRollNo(), this);
        }
        /*
    }//GEN-LAST:event_chatsListMouseClicked
*/
   public JFrame getFrame()
   {
       return this;
   }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea chatBox;
    private javax.swing.JList chatsList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea messageField;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JButton sendBtn;
    public javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
